### ISSUE TITLE
Bug: Attributes' value with spread operator is not being parsed

### ISSUE THREAD

**Issue by michalsnik** [mysticatea/vue-eslint-parser#30]
I confirmed the following issue: https://github.com/vuejs/eslint-plugin-vue/issues/497

This code:
```html
<input v-on="{ ...$listeners }" />
```

results in the following AST:
```
         - type: VAttribute
            directive: true
            key:
              type: VDirectiveKey
              name: on
              argument: null
              modifiers: []
              shorthand: false
              raw:
                name: on
                argument: null
                modifiers: []
            value:
              type: VExpressionContainer
              expression: null
              references: []
```

Whereas for this:
```html
<input v-on="{ click: action }" />
```

we get the correct AST with `VOnExpression`:
```
         - type: VAttribute
            directive: true
            key:
              type: VDirectiveKey
              name: on
              argument: null
              modifiers: []
              shorthand: false
              raw:
                name: on
                argument: null
                modifiers: []
            value:
              type: VExpressionContainer
              expression:
                type: VOnExpression
                body:
                  - type: BlockStatement
                    body:
                      - type: LabeledStatement
                        body:
                          type: ExpressionStatement
                          expression:
                            type: Identifier
                            name: action
                        label:
                          type: Identifier
                          name: click
              references:
                - id:
                    type: Identifier
                    name: action
                  mode: r
```

Can we parse objects with spread operators inside attributes' values properly? Same applies to attributes and bindings.

**Comment by mysticatea** [comment]
Thank you for this issue.

Try `parserOptions.ecmaVersion: 2018`.

**Comment by michalsnik** [comment]
Thanks!

**Comment by mysticatea** [comment]
I confirmed that the paths of `v-on` and `v-on:foo` are different. `v-on:foo="{}"` becomes a block statement, but `v-on="{}"` becomes an object expression. I  will fix `vue-eslint-parser`.

**Comment by mysticatea** [comment]
I'm thinking about AST, `v-on="{ click: action }"` skips `VOnExpression` node because it's not supporting statements.

It will be:

```
         - type: VAttribute
            directive: true
            key:
              type: VDirectiveKey
              name: on
              argument: null
              modifiers: []
              shorthand: false
              raw:
                name: on
                argument: null
                modifiers: []
            value:
              type: VExpressionContainer
              expression:
                type: ObjectExpression
                properties:
                  - type: Property
                    computed: false
                    method: false
                    shorthand: false
                    key:
                      type: Identifier
                      name: click
                    value:
                      type: Identifier
                      name: action
              references:
                - id:
                    type: Identifier
                    name: action
                  mode: r
```

Probably we will have to modify some rules which are checking `v-on` attribute.
